// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6C0N8deIBybkADWG1j4Vftt5Dx8LL7QY',
    appId: '1:1087996399159:web:3596229d6d1fc82fed39b2',
    messagingSenderId: '1087996399159',
    projectId: 'weather-app-flutter-b626f',
    authDomain: 'weather-app-flutter-b626f.firebaseapp.com',
    storageBucket: 'weather-app-flutter-b626f.appspot.com',
    measurementId: 'G-JJD0YRFJHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYPxCa86ju9nEFr4Q0i2PL8xgR9HWX5M',
    appId: '1:1087996399159:android:be5906a57b87267eed39b2',
    messagingSenderId: '139525109981',
    projectId: 'flutterfirst-130c5',
    storageBucket: 'flutterfirst-130c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjM-76nifGJQBXDtUhxnBnZHx5UPcoBlc',
    appId: '1:1087996399159:ios:9f75d7489a727882ed39b2',
    messagingSenderId: '1087996399159',
    projectId: 'weather-app-flutter-b626f',
    storageBucket: 'weather-app-flutter-b626f.appspot.com',
    iosBundleId: 'com.example.weatherappflutterNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjM-76nifGJQBXDtUhxnBnZHx5UPcoBlc',
    appId: '1:1087996399159:ios:9f75d7489a727882ed39b2',
    messagingSenderId: '1087996399159',
    projectId: 'weather-app-flutter-b626f',
    storageBucket: 'weather-app-flutter-b626f.appspot.com',
    iosBundleId: 'com.example.weatherappflutterNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6C0N8deIBybkADWG1j4Vftt5Dx8LL7QY',
    appId: '1:1087996399159:web:44d7d3c37a86a7cbed39b2',
    messagingSenderId: '1087996399159',
    projectId: 'weather-app-flutter-b626f',
    authDomain: 'weather-app-flutter-b626f.firebaseapp.com',
    storageBucket: 'weather-app-flutter-b626f.appspot.com',
    measurementId: 'G-H71Z8QD2BB',
  );
}
